# Generated by Django 3.0.5 on 2020-05-10 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 17, 16, 33, 240140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 17, 16, 33, 241256, tzinfo=utc), editable=False),
        ),
    ]
